In [11]:
import qiskit
from qiskit import QuantumCircuit
from qiskit.quantum_info import Operator
import numpy as np
from qiskit.tools.visualization import plot_histogram

In [12]:
circuit = QuantumCircuit(2,2)
circuit.h(0)
circuit.cx(0,1)
circuit.measure([0,1], [0,1])
circuit.draw()

┌───┐     ┌─┐   
q_0: ┤ H ├──■──┤M├───
     └───┘┌─┴─┐└╥┘┌─┐
q_1: ─────┤ X ├─╫─┤M├
          └───┘ ║ └╥┘
c: 2/═══════════╩══╩═
                0  1

In [13]:
num_shots = 1024
simulator = qiskit.providers.aer.QasmSimulator()
executed_job = qiskit.execute(circuit, simulator, shots=num_shots)
r = executed_job.result()
print("r: ", type(r))
print("success:", r.success)
result_dict = r.to_dict()
print("result_dict:", type(result_dict))
print("executed_job:", executed_job)

r:  <class 'qiskit.result.result.Result'>
success: True
result_dict: <class 'dict'>
executed_job: <qiskit.providers.aer.aerjob.AerJob object at 0x7fba95d1aca0>


In [17]:
counts = r.get_counts(circuit)
print("counts: ", type(counts))
plot_histogram(counts, title='Bell-State counts')
print(counts)
print(counts["00"])
print(counts.keys())

counts:  <class 'qiskit.result.counts.Counts'>
{'00': 514, '11': 510}
514
dict_keys(['00', '11'])


In [10]:
counts_array = np.zeros(shape=(4,4))
count_strings = ["0000","0100","0001","0101"]

for i in range(len(count_strings)):
    sl = [int(d) for d in count_strings[i]]
    counts_array[i] = sl

print(counts_array)    
print(counts_array[1][1])
print(counts_array[:,0])
print(counts_array[:,1])
print(counts_array[:,2])
print(counts_array[:,3])

[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 1.]]
1.0
[0. 0. 0. 0.]
[0. 1. 0. 1.]
[0. 0. 0. 0.]
[0. 0. 1. 1.]


In [29]:
sums = np.sum(counts_array,0)
sums

array([0., 2., 0., 2.])

In [14]:
l = [1,2,3,4]
sum(l)

10

In [31]:
qubits = []
for i in range(len(sums)):
    if sums[i]==0:
        qubits.append(i)
qubits


[0, 2]